src/Chirp/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Identity;
using Chirp.Models;
using Chirp.ViewModels;
using System.Security.Claims;
using AutoMapper;
using Microsoft.Extensions.Logging;
using System.Net;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Chirp.Controllers
{
    public class AuthController : Controller
    {
        private SignInManager<ChirpUser> m_signInManager;
        private UserManager<ChirpUser> m_userManager;
        private ILogger<AuthController> m_logger;

        public AuthController(SignInManager<ChirpUser> a_signInManager, UserManager<ChirpUser> a_userManager, ILogger<AuthController> a_logger)
        {
            m_signInManager = a_signInManager;
            m_userManager = a_userManager;
            m_logger = a_logger;
        }

        [HttpGet]
        public IActionResult Login()
        {
            if (User.Identity.IsAuthenticated)
            {
                return RedirectToAction("Chirps", "App");
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(LoginViewModel vm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var signInResult = await m_signInManager.PasswordSignInAsync(vm.Username, vm.Password, true, false);

                if (signInResult.Succeeded)
                {
                    if (String.IsNullOrWhiteSpace(returnUrl))
                    {
                        return RedirectToAction("Chirps", "App");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Username or password incorrect");
                }
            }

            return View();
        }

        [HttpGet]
        public async Task<JsonResult> CurrentUser()
        {
            try
            {
                if (User.Identity.IsAuthenticated)
                {
                    var user = await m_userManager.FindByIdAsync(User.GetUserId());
                    return Json(Mapper.Map<ChirpUserViewModel>(user));
                }

                Response.StatusCode = (int)HttpStatusCode.Forbidden;
                return Json(new { Message = "You are not logged in" });
            }
            catch (Exception ex)
            {
                m_logger.LogError("Failed to get current user", ex);
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(new { Message = ex.Message });
            }
        }

        public async Task<ActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await m_signInManager.SignOutAsync();
            }

            return RedirectToAction("Index", "App");
        }
    }
}

src/Chirp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Chirp - @ViewBag.Title</title>
    <meta charset="utf-8" />

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div id="sidebar">
        @if (User.Identity.IsAuthenticated)
        {
            <img class="profilepicture" src="~/img/prof.jpg" alt="Profile Picture" />
            <span id="username">@User.Identity.Name</span>
        }
        
        <ul class="nav">
            <li class="active"><a asp-controller="App" asp-action="Index">Home</a></li>
            <li><a asp-controller="App" asp-action="Chirps">Chirp Feed</a></li>
            <li><a asp-controller="App" asp-action="About">About</a></li>
            <li><a asp-controller="App" asp-action="Contact">Contact</a></li>
            @if (User.Identity.IsAuthenticated)
            {
                <li><a asp-controller="Auth" asp-action="Logout">Logout</a></li>
            }
        </ul>
    </div>

    <div id="wrapper" class="container-fluid">
        <div id="main">
            <div>
                @RenderBody()
            </div>
            <div id="footer" class="container-fluid">
                <div class="navbar navbar-inverse navbar-fixed-bottom">
                    <h4 class="text-center text-info"> &copy; 2015 Steve Fallon</h4>
                </div>
            </div>
        </div>
    </div>
    @RenderSection("Scripts", false)
</body>
</html>